{{- if and (eq .Values.auth.mode "token") (not .Values.auth.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-explorer.fullname" . }}-auth
  labels: {{- include "nats-explorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "auth.token is required with auth.mode=token and no auth.secretName" .Values.auth.token | quote }}
{{- end }}
